---
- name: Raspberry Pi configuration
  vars:
    common_mount_options: uid=1000,gid=1000,nodiratime,noexec,rw,nosuid,nodev,auto,async,relatime,nofail
    timezone: Australia/Melbourne
    apt_packages:
      - exfat-fuse
      - exfat-utils
      - git
      - hfsplus
      - hfsprogs
      - hfsutils
      - python3
      - sysstat
      - vim
    apt_packages_to_purge:
    mounts:
      - label: TMc
        fstype: hfsplus
        dir: /mnt/tmachine
        options: "force,{{ common_mount_options }}"
      - label: Backup
        fstype: exfat
        dir: /mnt/backup
        options: "{{ common_mount_options }}"
      - label: Media
        fstype: exfat
        dir: /mnt/media
        options: "{{ common_mount_options }}"
    nfs_mounts:
      - /mnt/media
      - /mnt/backup
    install_cache_dir: /opt/install
    swap_size: 4096
  hosts: all
  user: pi
  tasks:
    - import_tasks: tasks/os.yml
    - import_tasks: tasks/services.yml
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/seafile.yml
