---
- name: Raspberry Pi configuration
  vars:
    common_mount_options: uid=1000,gid=1000,nodiratime,noexec,rw,nosuid,nodev,auto,async,relatime,nofail
    timezone: Australia/Melbourne
    apt_packages:
      - git
      - python3
      - hfsplus
      - hfsutils
      - hfsprogs
      - exfat-fuse
      - exfat-utils
    mounts:
      - uuid: 8ffc0ba7-06eb-3a67-963c-85fc3860a00c
        fstype: hfsplus
        dir: /mnt/tmachine
        options: "force,{{ common_mount_options }}"
      - uuid: B4D9-9D02
        fstype: exfat
        dir: /mnt/backup
        options: "{{ common_mount_options }}"
      - uuid: C4EF-D50B
        fstype: exfat
        dir: /mnt/media
        options: "{{ common_mount_options }}"
  hosts: all
  user: pi
  tasks:
    - import_tasks: tasks/os.yml
    #- import_tasks: tasks/docker.yml
    - import_tasks: tasks/nfs.yml

    - name: reboot
      shell: "sleep 1 && shutdown -r now +1"
      when: false
