---
- name: Raspberry Pi configuration
  vars:
    mount_options: nodiratime,noexec,rw,nosuid,nodev,auto,async,relatime,nofail
    timezone: Australia/Melbourne
    apt_packages:
      - avahi-daemon
      - avahi-dnsconfd
      - dphys-swapfile
      - exfat-fuse
      - exfat-utils
      - git
      - neovim
      - net-tools
      - python3
      - python3-pip
      - samba
      - samba-vfs-modules
      - sysstat
    apt_packages_to_purge:
    mounts:
      - label: 4
        fstype: ext4
        dir: /mnt/4
        options: "defaults,noatime"
      - label: 8
        fstype: exfat
        dir: /mnt/8
        options: "uid=1000,gid=1000,{{ mount_options }}"
    install_cache_dir: /opt/install
    swap_size: 4096
  hosts: all
  user: ubuntu
  tasks:
    - import_tasks: tasks/os.yml
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/services.yml
