---
- name: Raspberry Pi configuration
  vars:
    mount_options: nodiratime,noexec,rw,nosuid,nodev,auto,async,relatime,nofail
    timezone: Australia/Melbourne
    apt_packages:
      - exfat-fuse
      - exfat-utils
      - git
      - python-pip
      - python-setuptools
      - python3
      - python3-pip
      - sysstat
      - neovim
    apt_packages_to_purge:
    mounts:
      - label: TMc
        fstype: ext4
        dir: /mnt/tmachine
        options: "{{ mount_options }}"
      - label: Backup
        fstype: exfat
        dir: /mnt/backup
        options: "uid=1000,gid=1000,{{ mount_options }}"
      - label: Media
        fstype: exfat
        dir: /mnt/media
        options: "uid=1000,gid=1000,{{ mount_options }}"
    install_cache_dir: /opt/install
    reboot: false
    swap_size: 4096
  hosts: all
  user: pi
  tasks:
    - import_tasks: tasks/os.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/services.yml
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/webdav.yml
