#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [ -f ./.env ]
then
  source ./.env
fi
rm -f entrypoint.retry
#ANSIBLE_SSH_PIPELINING=1 ansible-playbook -i "$1", -vvvv -C entrypoint.yml || rm -f entrypoint.retry
ANSIBLE_SSH_PIPELINING=1 ansible-playbook -i "$1", -v entrypoint.yml || rm -f entrypoint.retry
