---
- name: Download docker install script
  get_url:
    url: https://get.docker.com
    dest: "{{ install_cache_dir }}/docker-install.sh"
    mode: "a+x"
  become: yes
  register: install_sh

- name: Run install script
  shell: /bin/sh "{{ install_cache_dir }}/docker-install.sh"
  become: yes
  when: install_sh.changed

- name: Set Docker to auto-start
  service:
    name: docker
    enabled: true
    state: started
  become: yes

- name: Add pi to the docker group
  user:
    name: pi
    groups: docker
  become: yes

- name: add pip docker package
  pip:
    name:
      - docker
      - docker-compose
  become: yes

- name: add systemd service template
  copy:
    src: docker_systemd.service
    dest: /etc/systemd/system/docker-compose@.service
  become: yes

- name: create individual service dir
  file:
    state: directory
    path: /etc/docker/compose/
  become: yes

- name: upload build context for containers
  synchronize:
    src: "../containers/{{ item }}/"
    dest: "/etc/docker/compose/{{ item }}/"
  become: true
  with_items:
    - acmesh
    - ddns
    - webdav
    - samba

- name: Build local images
  docker_image:
    path: "/etc/docker/compose/{{ item }}/"
    name: "xiaket/{{ item }}"
    tag: latest
  become: true
  with_items:
    - acmesh
    - ddns
    - webdav
    - samba

- name: create cronjob to cleanup docker system every day.
  cron:
    name: "docker system cleanup."
    special_time: daily
    job: "docker system prune -f"
  become: yes

- name: restart samba service
  systemd:
    name: "docker-compose@samba"
    enabled: true
    state: restarted
  become: true
