---
- name: Download docker install script
  get_url:
    url: https://get.docker.com
    dest: "{{ install_cache_dir }}/docker-install.sh"
    mode: "a+x"
  become: yes
  register: install_sh

- name: Run install script
  shell: /bin/sh "{{ install_cache_dir }}/docker-install.sh"
  become: yes
  when: install_sh.changed

- name: Set Docker to auto-start
  service:
    name: docker
    enabled: true
    state: started
  become: yes

- name: Add pi to the docker group
  user:
    name: pi
    groups: docker
  become: yes

- name: add pip docker package
  pip:
    name:
      - docker
      - docker-compose
  become: yes

- name: add systemd service template
  copy:
    src: docker_systemd.service
    dest: /etc/systemd/system/docker-compose@.service
  become: yes

- name: create individual service dir
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /etc/docker/compose/
    - /etc/docker/images/
  become: yes

- name: create cronjob to cleanup docker system every day.
  cron:
    name: "docker system cleanup."
    special_time: daily
    job: "docker system prune -f"
  become: yes
