---
- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present
  become: true

- name: configure nfs service
  lineinfile:
    path: /etc/exports
    line: "{{ item }} {{ ansible_default_ipv4.network }}/24(rw,sync,wdelay,insecure,anonuid=1000,anongid=1000,all_squash)"
    state: present
    create: true
  with_items: "{{ nfs_mounts }}"
  become: yes

- name: Ensure nfs is running.
  service:
    name: nfs-kernel-server
    state: started
    enabled: true
  become: true
