---
- name: create cache_install_dir
  file:
    state: directory
    path: "{{ install_cache_dir }}"
  become: yes

- name: set timezone
  timezone:
    name: "{{ timezone }}"
  become: yes

- name: Update All Packages
  apt:
    update_cache: yes
    upgrade: "yes"
  become: yes
  register: package_updates

- name: ask user for confirmation before reboot
  pause:
    prompt: "Do you want to reboot (yes/no)?"
  when: package_updates.changed
  register: reboot
  delegate_to: localhost

- name: reboot
  shell: "sleep 3 && reboot"
  when: package_updates.changed and reboot.user_input | bool
  async: 1
  poll: 0
  become: yes

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 2
    delay: 5
    timeout: 300
  when: package_updates.changed and reboot.user_input | bool

- name: install packages
  apt:
    name: "{{ apt_packages }}"
    state: present
    install_recommends: no
  become: yes

- name: configure mount points
  mount:
    path: "{{ item.dir }}"
    src: "LABEL={{ item.label }}"
    fstype: "{{ item.fstype }}"
    state: mounted
    opts: "{{ item.options }}"
  become: yes
  with_items: "{{ mounts }}"

- name: remove profile scripts
  file:
    path: "/etc/profile.d/{{ item }}"
    state: absent
  with_items:
    - bash_completion.sh
    - sshpwd.sh
    - wifi-country.sh
  become: yes
