---
# SSH
- name: configure ssh service - absent
  lineinfile:
    path: ~/sshd_config
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^#.*'
    - '^\s?$'
    - 'X11Forwarding yes'

- name: configure ssh service - present
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
    state: present
  with_items:
    - 'KbdInteractiveAuthentication no'
    - 'PasswordAuthentication no'
    - 'PubkeyAuthentication yes'
  become: yes

- name: restart ssh service
  service:
    name: ssh
    state: restarted
  become: true
  changed_when: false

# DPHYS: swap as a service
- name: setup swap size
  lineinfile:
    path: /etc/dphys-swapfile
    line: "{{ item }}"
    state: present
  become: true
  with_items:
    - "CONF_SWAPSIZE={{ swap_size }}"
    - "CONF_MAXSWAP={{ swap_size }}"
  register: swap_size

- name: enable swap size
  service:
    name: dphys-swapfile
    state: restarted
  become: true
  when: swap_size.changed

# sysstat
- name: configure sar to enable statistics gathering
  lineinfile:
    path: /etc/default/sysstat
    regex: '^ENABLED='
    line: 'ENABLED="true"'
    state: present
  become: true
  register: sysstat_service

- name: reload sysstat service
  service:
    name: sysstat
    state: restarted
  become: true
  when: sysstat_service.changed

- name: Add cron job to update A record of home.xiaket.org
  cron:
    name: "Dynamic DNS"
    special_time: hourly
    job: "docker run --env-file /etc/docker/images/ddns/.env xiaket/ddns"
  become: yes

# rsync whip
- name: copy scripts over
  synchronize:
    src: "../scripts/"
    dest: /usr/local/bin/
  become: True

- name: run rsync whip hourly
  cron:
    name: "Rsync whip"
    special_time: hourly
    job: /usr/local/bin/rsync_whip
    user: pi
