---
# NFS		
- name: Install NFS utilities		
  apt:		
    name:		
      - nfs-common		
      - nfs-kernel-server		
    state: present		
  become: true		
  register: nfs_package		

- name: configure nfs service		
  lineinfile:		
    path: /etc/exports		
    line: "{{ item }} {{ ansible_default_ipv4.network }}/24(rw,sync,wdelay,no_subtree_check,insecure,anonuid=1000,anongid=1000,all_squash)"		
    state: present		
    create: true		
  with_items:
    - /mnt/4
    - /mnt/8
  become: yes		

- name: Restart NFS if required.		
  service:		
    name: nfs-kernel-server		
    state: restarted		
  become: true		
  when: nfs_package.changed		

- name: Ensure nfs is running.		
  service:		
    name: nfs-kernel-server		
    state: started		
    enabled: true		
  become: true

# SSH
- name: configure ssh service - absent
  lineinfile:
    path: ~/sshd_config
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^#.*'
    - '^\s?$'
    - 'X11Forwarding yes'

- name: configure ssh service - present
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
    state: present
  with_items:
    - 'KbdInteractiveAuthentication no'
    - 'PasswordAuthentication no'
    - 'PubkeyAuthentication yes'
  become: yes

- name: restart ssh service
  service:
    name: ssh
    state: restarted
  become: true
  changed_when: false

# DPHYS: swap as a service
- name: setup swap size
  lineinfile:
    path: /etc/dphys-swapfile
    line: "{{ item }}"
    state: present
  become: true
  with_items:
    - "CONF_SWAPSIZE={{ swap_size }}"
    - "CONF_MAXSWAP={{ swap_size }}"
  register: swap_size

- name: enable swap size
  service:
    name: dphys-swapfile
    state: restarted
  become: true
  when: swap_size.changed

# sysstat
- name: configure sar to enable statistics gathering
  lineinfile:
    path: /etc/default/sysstat
    regex: '^ENABLED='
    line: 'ENABLED="true"'
    state: present
  become: true
  register: sysstat_service

- name: reload sysstat service
  service:
    name: sysstat
    state: restarted
  become: true
  when: sysstat_service.changed

- name: add env file for ddns service
  lineinfile:
    path: /etc/docker/compose/ddns/.env
    line: "NAMESILO_APIKEY={{ lookup('env','NAMESILO_APIKEY') }}"
    create: yes
  become: true

- name: Add cron job to update A record of home.xiaket.org
  cron:
    name: "Dynamic DNS"
    special_time: hourly
    job: "docker run --env-file /etc/docker/compose/ddns/.env xiaket/ddns"
  become: yes

# rsync whip
- name: copy scripts over
  synchronize:
    src: "../scripts/"
    dest: /usr/local/bin/
  become: True

- name: add PyYAML for python3
  pip:
    executable: pip3
    name:
      - PyYAML
  become: yes

- name: run rsyncer every minutes
  cron:
    name: "Rsyncer"
    minute: "*"
    job: /usr/local/bin/rsyncer
    user: "{{ ansible_user_id }}"

# a poor man's multi disk backup
- name: run back-upper every minutes
  cron:
    name: "Image backup service"
    minute: "*"
    job: /usr/local/bin/back-upper >/tmp/back-upper.log 2>&1
    user: root
  become: yes

# samba
- name: copy avahi configuration file over
  copy:
    src: timemachine.service
    dest: /etc/avahi/services/timemachine.service
  become: yes

- name: copy samba configuration file over
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
  become: yes

- name: restart avahi/samba service
  service:
    name: "{{ item }}"
    state: started
  become: true
  with_items:
    - avahi-daemon
    - smbd
