# TimeMachine
- name: setup variables
  set_fact:
    version: 3.1.11
    packages:
      - libevent-dev
      - libssl-dev
      - libgcrypt11-dev
      - libkrb5-dev
      - libdb-dev
      - libtdb-dev
      - libcrack2-dev
    tmachine_dir: /mnt/tmachine

- name: Determine the current version of netatalk
  shell: "afpd -v | head -n 1 | awk '{print $2}'"
  register: afpd_version
  become: yes
  failed_when: false

- name: set skip
  set_fact:
    run_install: True
  when: >
      afpd_version.rc != 0 or afpd_version.stdout != version

- name: Download release file
  get_url:
    url: "http://prdownloads.sourceforge.net/netatalk/netatalk-{{ version }}.tar.gz"
    dest: /tmp/netatalk.tgz
  when: run_install is defined

- name: Extract release file
  unarchive:
    src: /tmp/netatalk.tgz
    remote_src: true
    dest: /tmp
  when: run_install is defined

- name: Install dependencies
  apt:
    pkg: "{{ packages }}"
    state: present
  become: yes

- name: configure
  command: ./configure --with-init-style=debian-systemd --without-libevent --with-cracklib --enable-krbV-uam --with-pam-confdir=/etc/pam.d --with-dbus-daemon=/usr/bin/dbus-daemon --with-dbus-sysconf-dir=/etc/dbus-1/system.d
  args:
    chdir: "/tmp/netatalk-{{ version }}/"
    creates: "/tmp/netatalk-{{ version }}/Makefile"
  when: run_install is defined

- name: make
  command: make
  args:
    chdir: "/tmp/netatalk-{{ version }}/"
  when: run_install is defined

- name: make install
  command: make
  args:
    chdir: "/tmp/netatalk-{{ version }}/"
  become: yes
  when: run_install is defined

- name: create avahi config file
  copy:
    src: tmc.service
    dest: /etc/avahi/services/afpd.service
  become: yes

- name: Create service configuration
  template:
    src: tmc_afp.conf.jinja2
    dest: /usr/local/etc/afp.conf
  become: yes

- name: configure nsswitch file
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: "hosts:.*"
    line: "hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4 mdns"
    state: present
  become: true

- name: reload related service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  become: true
  when: run_install is defined
  with_items:
    - avahi-daemon
    - netatalk
