- name: disable motd messages
  file:
    path: '~/.hushlogin'
    state: touch
  changed_when: false

- name: create ssh dir and control master dir
  file:
    state: directory
    path: ~/.ssh/sockets
    mode: 0700

- name: create ssh config file
  copy:
    src: ssh_config
    dest: ~/.ssh/config
