---
- name: install passlib so we can generate passwords.
  pip:
    name: passlib
  become: true

- name: upload build context for webdav and acmesh
  synchronize:
    src: "../containers/{{ item }}/"
    dest: "/etc/docker/compose/{{ item }}/"
  become: true
  with_items:
    - webdav
    - acmesh

- name: generate password file
  htpasswd:
    path: /etc/docker/compose/webdav/htpasswd
    name: irene
    password: "{{ lookup('env','HTPWD_IRENE') }}"
    owner: root
    group: 102
    mode: 0640
  become: true

- name: check certificate file
  stat:
    path: /var/acme/home.xiaket.org/home.xiaket.org.key
  become: true
  register: webdav_ssl_key

- name: create hard link for httpd.conf to start HTTP server
  file:
    src: /etc/docker/compose/webdav/httpd.conf.http
    dest: /etc/docker/compose/webdav/httpd.conf
    force: true
    state: hard
  become: true
  when: not webdav_ssl_key.stat.exists

- name: create acme data dir
  file:
    path: /var/acme
    state: directory
  become: true

- name: enable webdav/acmesh service
  systemd:
    name: "docker-compose@{{ item }}"
    enabled: true
    state: started
  become: true
  with_items:
    - webdav
    - acmesh

- name: Generate https certificate for home.xiaket.org
  command: docker exec acme --issue -d home.xiaket.org  -w /tmp/webroot
  args:
    creates: /var/acme/home.xiaket.org/home.xiaket.org.key
  become: true

- name: Renew https certificate for home.xiaket.org
  command: docker exec acme --renew --force -d home.xiaket.org  -w /tmp/webroot
  become: true
  when: false
  changed_when: false

- name: create hard link for httpd.conf to start HTTPS server
  file:
    src: /etc/docker/compose/webdav/httpd.conf.https
    dest: /etc/docker/compose/webdav/httpd.conf
    force: true
    state: hard
  become: true

- name: restart webdav service
  systemd:
    name: "docker-compose@webdav"
    enabled: true
    state: restarted
  become: true
