---
- name: install passlib so we can generate passwords.
  pip:
    name: passlib
  become: true

- name: upload build context
  synchronize:
    src: ../containers/webdav/
    dest: /etc/docker/compose/webdav/
  become: true

- htpasswd:
    path: /etc/docker/compose/webdav/htpasswd
    name: irene
    password: "{{ lookup('env','HTPWD_IRENE') }}"
    owner: root
    group: www-data
    mode: 0640
  become: true

- name: enable webdav service
  systemd:
    name: 'docker-compose@webdav'
    enabled: true
    state: started
  become: true

- name: upload build context
  synchronize:
    src: ../containers/ddns/
    dest: /etc/docker/images/ddns/
  become: true

- name: Build an image and push it to a private repo
  docker_image:
    path: /etc/docker/images/ddns/
    name: xiaket/ddns
    tag: latest

- name: Add cron job to update A record of home.xiaket.org
  cron:
    name: "Dynamic DNS"
    special_time: hourly
    job: "docker run --env-file /etc/docker/images/ddns/.env xiaket/ddns"
  become: yes
