---
- name: install passlib so we can generate passwords.
  pip:
    name: passlib
  become: true

- name: upload build context for webdav
  synchronize:
    src: ../containers/webdav/
    dest: /etc/docker/compose/webdav/
  become: true

- htpasswd:
    path: /etc/docker/compose/webdav/htpasswd
    name: irene
    password: "{{ lookup('env','HTPWD_IRENE') }}"
    owner: root
    group: www-data
    mode: 0640
  become: true

- name: enable webdav service
  systemd:
    name: 'docker-compose@webdav'
    enabled: true
    state: started
  become: true

- name: upload build context for images
  synchronize:
    src: "../containers/{{ item }}/"
    dest: "/etc/docker/images/{{ item }}/"
  become: true
  with_items:
    - ddns
    - acmesh

- name: Build local images
  docker_image:
    path: "/etc/docker/images/{{ item }}/"
    name: "xiaket/{{ item }}"
    tag: latest
  with_items:
    - ddns
    - acmesh

- name: Add cron job to update A record of home.xiaket.org
  cron:
    name: "Dynamic DNS"
    special_time: hourly
    job: "docker run --env-file /etc/docker/images/ddns/.env xiaket/ddns"
  become: yes
