version: '3'
services:
  samba:
    build: .
    container_name: samba
    volumes:
      - /mnt/media:/mnt/media
      - /mnt/backup:/mnt/backup
      - /mnt/tmachine:/mnt/tmachine
      - ./smb.conf:/etc/samba/smb.conf
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    restart: always
