#!/usr/bin/env python3
import errno
import os
import subprocess
import sys

LOCK = "/tmp/back-upper.lock"


class Rsync:
    def lock(self):
        try:
            self.fd = os.open(LOCK, os.O_CREAT|os.O_EXCL|os.O_RDWR)
            print("Acquired Lock.")
        except OSError as err:
            if err.errno != errno.EEXIST:
                raise
            print("Lock exists, exiting.")
            sys.exit(0)

    def unlock(self):
        os.close(self.fd)
        os.remove(LOCK)

    def sync(self):
        command = [
            "rsync",
            "--progress",
            "-av",
            "/mnt/8/图片/",
            "/mnt/4/Themes/Pictures/图片/",
        ]
        print("Running rsync: ", " ".join(command))
        try:
            subprocess.run(command)
        except:
            self.unlock()
            sys.exit(1)

    def main(self):
        self.lock()
        self.sync()
        self.unlock()


if __name__ == "__main__":
    rsync = Rsync()
    rsync.main()
